version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/quagga/r1/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/supervisord_bgp.conf:/etc/supervisord.conf:ro
    image: bgp:20180508
    privileged: true
    ports:
      #admin
      - 10011:2601
      #ospf
      - 10012:2604
      #ospf ipv6
      - 10013:2606
      #bgp
      - 10014:2605
    networks:
      oam1:
        ipv4_address: 192.168.10.11
        ipv6_address: 2001:aaaa:bbbb:1::11
      oam2:
        ipv4_address: 192.168.2.11
        ipv6_address: 2001:aaaa:bbbb:2::11
      oam3:
        ipv4_address: 192.168.3.11
        ipv6_address: 2001:aaaa:bbbb:3::11
      oam4:
        ipv4_address: 192.168.4.11
        ipv6_address: 2001:aaaa:bbbb:4::11
     
          
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf
      - 10022:2604
      #ospf ipv6
      - 10023:2606
    networks:
      oam3:
        ipv4_address: 192.168.3.12
        ipv6_address: 2001:aaaa:bbbb:3::12
      oam5:
        ipv4_address: 192.168.5.12
        ipv6_address: 2001:aaaa:bbbb:5::12
      nr2:
        ipv4_address: 172.16.2.12
        ipv6_address: 2001:aaaa:bbbb:7::12
            
  r3:
    build: .
    volumes:
      - ./volumes/quagga/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r3/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10024:2601
      #ospf
      - 10025:2604
      #ospf ipv6
      - 10026:2606
    networks:
      oam4:
        ipv4_address: 192.168.4.13
        ipv6_address: 2001:aaaa:bbbb:4::13
      oam5:
        ipv4_address: 192.168.5.13
        ipv6_address: 2001:aaaa:bbbb:5::13
      nr3:
        ipv4_address: 172.16.3.13
        ipv6_address: 2001:aaaa:bbbb:8::13
  r4:
    build: .
    volumes:
      - ./volumes/quagga/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r4/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/supervisord_bgp2.conf:/etc/supervisord.conf:ro
    image: bgp:20180508
    privileged: true
    ports:
      #admin
      - 10055:2601
      #bgp
      - 10056:2605
    networks:
      oam1:
        ipv4_address: 192.168.10.14
        ipv6_address: 2001:aaaa:bbbb:1::14
      oam6:
        ipv4_address: 192.168.6.14
        ipv6_address: 2001:aaaa:bbbb:6::14
      nr4:
        ipv4_address: 172.16.4.14
        ipv6_address: 2001:aaaa:bbbb:9::14
  
  r5:
    build: .
    volumes:
      - ./volumes/quagga/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r5/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/supervisord_bgp2.conf:/etc/supervisord.conf:ro
    image: bgp:20180508
    privileged: true
    ports:
      #admin
      - 10030:2601
      #bgp
      - 10031:2605
    networks:
      oam2:
        ipv4_address: 192.168.2.15
        ipv6_address: 2001:aaaa:bbbb:2::15
      oam6:
        ipv4_address: 192.168.6.15
        ipv6_address: 2001:aaaa:bbbb:6::15
      nr5:
        ipv4_address: 172.16.5.15
        ipv6_address: 2001:aaaa:bbbb:10::15

#----------------------------------------

  h1:
    image: alpine:latest
    command: top
    privileged: true
    networks:
      nr3:
         ipv4_address: 172.16.3.20
         ipv6_address: 2001:aaaa:bbbb:8::20

        
  h2:
    image: alpine:latest
    command: top
    privileged: true
    networks:
       nr4:
         ipv4_address: 172.16.4.20
         ipv6_address: 2001:aaaa:bbbb:9::20
        
  h3:
    image: alpine:latest
    command: top
    privileged: true
    networks:
       nr5:
         ipv4_address: 172.16.5.20   
         ipv6_address: 2001:aaaa:bbbb:10::20
  
  server1:
    image: nginx:alpine
    privileged: true
    networks:
       nr2:
         ipv4_address: 172.16.2.20
         ipv6_address: 2001:aaaa:bbbb:7::20       

networks:
  oam1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
        - subnet: 2001:aaaa:bbbb:1::0/64

  oam2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
        - subnet: 2001:aaaa:bbbb:2::0/64
  
  oam3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
        - subnet: 2001:aaaa:bbbb:3::0/64

  oam4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
        - subnet: 2001:aaaa:bbbb:4::0/64 
  
  oam5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
        - subnet: 2001:aaaa:bbbb:5::0/64
  
  oam6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.6.0/24
        - subnet: 2001:aaaa:bbbb:6::0/64 

#-----------------------------------------------

  nr2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
        - subnet: 2001:aaaa:bbbb:7::0/64
  nr3:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
        - subnet: 2001:aaaa:bbbb:8::0/64
  
  nr4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.4.0/24
        - subnet: 2001:aaaa:bbbb:9::0/64
  nr5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.5.0/24
        - subnet: 2001:aaaa:bbbb:10::0/64

