version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10011:2601
      #ospf
      - 10012:2604
      #ospf ipv6
      - 10013:2606
    networks:
      n1:
        ipv4_address: 192.108.1.11 # Conecta R2
        # ipv6_address: ::
      n3:
        ipv4_address: 192.108.3.11  # Conecta R3
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf
      - 10022:2604
      #ospf ipv6
      - 10024:2606
    networks:
      n1:
        ipv4_address: 192.108.1.12 # Conecta R1
      n2:
        ipv4_address: 192.108.2.12 # Conecta a H1, H2, H3
      n4:
        ipv4_address: 192.108.4.12 # Conecta R3
  r3:
    build: .
    volumes:
      - ./volumes/quagga/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r3/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10031:2601
      #ospf
      - 10032:2604
      #ospf ipv6
      - 10033:2606
    networks:
      n3:
        ipv4_address: 192.108.3.13 # Conecta R1
      n4:
        ipv4_address: 192.108.4.13 # Conecta R2
      n5:
        ipv4_address: 192.108.5.13 # Conecta R5
      n8:      
        ipv4_address: 192.108.8.13 # Conecta R4
  r4:
    build: .
    volumes:
      - ./volumes/quagga/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r4/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10041:2601
      #ospf
      - 10042:2604
      #ospf ipv6
      - 10043:2606
    networks:
      n7:
        ipv4_address: 192.108.7.14 # Conecta H4
      n8:
        ipv4_address: 192.108.8.14 # Conecta R4
      n9:
        ipv4_address: 192.108.9.14 # Conecta R5
  r5:
    build: .
    volumes:
      - ./volumes/quagga/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r5/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20190321
    privileged: true
    ports:
      #admin
      - 10051:2601
      #ospf
      - 10052:2604
      #ospf ipv6
      - 10053:2606
    networks:
      n5:
        ipv4_address: 192.108.5.15 # Conecta R3
      n6:
        ipv4_address: 192.108.6.15 # conecta H5
      n9:
        ipv4_address: 192.108.9.15 # Conecta R4

# hosts
  h1:
    volumes: 
      - './volumes/hosts/h1_networks:/etc/network/interfaces:ro'
    image: alpine
    privileged: true # supongo
    command:  ash -c "ip route del default && ip route add default via 192.108.2.12 && top"
    networks:
      n2:
        ipv4_address: 192.108.2.10
  h2:
    volumes: 
      - './volumes/hosts/h2_networks:/etc/network/interfaces:ro'
    image: alpine
    privileged: true # supongo
    command: ash -c "ip route del default && ip route add default via 192.108.2.12 && top"
    networks:
      n2:
        ipv4_address: 192.108.2.11
  h3:
    volumes: 
      - './volumes/hosts/h3_networks:/etc/network/interfaces:ro'
    image: alpine
    privileged: true # supongo
    command: ash -c "ip route del default && ip route add default via 192.108.2.12 && top"
    networks:
      n2:
        ipv4_address: 192.108.2.13
  h4:
    volumes: 
      - './volumes/hosts/h4_networks:/etc/network/interfaces:ro'
    image: alpine
    privileged: true
    command: ash -c "ip route del default && ip route add default via 192.108.7.14 && top"
    networks:
      n7:
        ipv4_address: 192.108.7.10
  h5:
    volumes: 
      - './volumes/hosts/h5_networks:/etc/network/interfaces:ro'
    image: alpine
    privileged: true
    command: ash -c "ip route del default && ip route add default via 192.108.6.15 && top"
    networks:
      n6:
        ipv4_address: 192.108.6.10

networks:
  n1:
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.1.0/24
  n2:      
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.2.0/24
  n3:      
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.3.0/24
  n4:
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.4.0/24
  n5:
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.5.0/24
  n6:
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.6.0/24
  n7:  
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.7.0/24
  n8:  
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.8.0/24
  n9:  
    driver: "bridge"
    ipam:
        driver: default
        config:
         - subnet: 192.108.9.0/24
